// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTam6dpOoIt0JrMA7wlKKyKb9eiqIb4CQ',
    appId: '1:412401205704:web:a01f391ccb7123d36a00fd',
    messagingSenderId: '412401205704',
    projectId: 'finger-app-c1653',
    authDomain: 'finger-app-c1653.firebaseapp.com',
    storageBucket: 'finger-app-c1653.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM7HxE3OStFOyitZtj4CrkCp0JqqMAaxw',
    appId: '1:412401205704:android:d6b6ea54dad530216a00fd',
    messagingSenderId: '412401205704',
    projectId: 'finger-app-c1653',
    storageBucket: 'finger-app-c1653.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOdoySVjy9pWbDJgxjcbC9kfScy9pruiE',
    appId: '1:412401205704:ios:ff53921456c26e5f6a00fd',
    messagingSenderId: '412401205704',
    projectId: 'finger-app-c1653',
    storageBucket: 'finger-app-c1653.firebasestorage.app',
    iosBundleId: 'com.example.fingerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOdoySVjy9pWbDJgxjcbC9kfScy9pruiE',
    appId: '1:412401205704:ios:ff53921456c26e5f6a00fd',
    messagingSenderId: '412401205704',
    projectId: 'finger-app-c1653',
    storageBucket: 'finger-app-c1653.firebasestorage.app',
    iosBundleId: 'com.example.fingerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTam6dpOoIt0JrMA7wlKKyKb9eiqIb4CQ',
    appId: '1:412401205704:web:9ac9d2ee75fd85d06a00fd',
    messagingSenderId: '412401205704',
    projectId: 'finger-app-c1653',
    authDomain: 'finger-app-c1653.firebaseapp.com',
    storageBucket: 'finger-app-c1653.firebasestorage.app',
  );
}
